version: '3.8'
services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    # image: mateusvn/goingcrazy:0.1
    hostname: api1
    depends_on:
      - postgres
    restart: on-failure
    expose:
      - 80
    environment:
      API_PORT: 80
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'
  
  api2:
    build: 
      context: .
      dockerfile: Dockerfile
    # image: mateusvn/goingcrazy:0.1
    hostname: api2
    expose:
      - 80
    depends_on:
      - postgres
    restart: on-failure
    environment:
      API_PORT: 80
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=350'
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1.5GB'

volumes:
  postgres-data: